// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAufslMzO-fFrFfXmLX0x3Uh3LW8npbYyI',
    appId: '1:272259835034:web:23626896433e7e90c76b23',
    messagingSenderId: '272259835034',
    projectId: 'lumina-3b95f',
    authDomain: 'lumina-3b95f.firebaseapp.com',
    storageBucket: 'lumina-3b95f.firebasestorage.app',
    measurementId: 'G-WHLXN255E8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTN6ef6WcB-qZLRF1nLUtK1dKlPEY8S8',
    appId: '1:272259835034:android:efdd13bad939d3d6c76b23',
    messagingSenderId: '272259835034',
    projectId: 'lumina-3b95f',
    storageBucket: 'lumina-3b95f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Vq0IMGu2CtpNjxmmdd7AByi0EnyCCvM',
    appId: '1:272259835034:ios:b8f7aa54cfc16285c76b23',
    messagingSenderId: '272259835034',
    projectId: 'lumina-3b95f',
    storageBucket: 'lumina-3b95f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Vq0IMGu2CtpNjxmmdd7AByi0EnyCCvM',
    appId: '1:272259835034:ios:b8f7aa54cfc16285c76b23',
    messagingSenderId: '272259835034',
    projectId: 'lumina-3b95f',
    storageBucket: 'lumina-3b95f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAufslMzO-fFrFfXmLX0x3Uh3LW8npbYyI',
    appId: '1:272259835034:web:e85e0ea84b5f4295c76b23',
    messagingSenderId: '272259835034',
    projectId: 'lumina-3b95f',
    authDomain: 'lumina-3b95f.firebaseapp.com',
    storageBucket: 'lumina-3b95f.firebasestorage.app',
    measurementId: 'G-ZQ4MW7T55N',
  );
}
